general:
  log_level: 'INFO'
  output_dir: ./outputs/
dataset:
  pems_data_path: './data/pems/PeMSD7_V_228.csv'
  pems_adj_path: './data/pems/PeMSD7_W_228.csv'
  pems_nodes: 228
  szfc_nodes: 500
  train_ratio: 0.6
  val_ratio: 0.2
model:
  name: stmgan
  num_steps: 4
  nb_filters:
  padding: same
  nb_stacks: 1
  dilations: [1,2,4]
  kernel_size: 3
  use_bn: True
  activation: relu
  dropout: 0.2
trainer:
  early_stopping: 2
  epochs: 15
  lr: 0.0001
  save_best_model: True
  
